version: '3.8'

# Services
services:
  # App
  app:
    build:
      context: .
      dockerfile: Dockerfile2
    environment:
      - PING_LISTEN_PORT=3000
    expose:
      - 3000
    deploy:
      replicas: 4
    networks:
      - app-network

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - app

# Network
networks:
  app-network:
    driver: bridge
